name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1


  validate-api:
    name: Validate STAC API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.10.4"
      - name: Set up Python
        run: uv python install
      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Build server
        run: go build -tags duckdb -o ./tmp/stac-server ./cmd/stac-server
      - name: Start server
        uses: JarvusInnovations/background-action@v1
        with:
          run: go run /tmp/stac-server -config-path ./example/duckdb/config.yaml
          wait-on: |
            http-get://localhost:8080/
          tail: true # true = stderr,stdout
          log-output-resume: stderr
          wait-for: 1m
      - name: Run stac-api-validator
        run: |
          uv run stac-api-validator \
            --root-url http://localhost:8080 \
            --conformance core --conformance collections \
            --collection naip
